# Generated by Django 3.1.6 on 2021-03-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlueTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('ban_1', models.CharField(default='', max_length=100)),
                ('ban_2', models.CharField(default='', max_length=100)),
                ('ban_3', models.CharField(default='', max_length=100)),
                ('ban_4', models.CharField(default='', max_length=100)),
                ('ban_5', models.CharField(default='', max_length=100)),
                ('pick_1', models.CharField(default='', max_length=100)),
                ('pick_2', models.CharField(default='', max_length=100)),
                ('pick_3', models.CharField(default='', max_length=100)),
                ('pick_4', models.CharField(default='', max_length=100)),
                ('pick_5', models.CharField(default='', max_length=100)),
                ('ban_champ_1', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_2', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_3', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_4', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_5', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_1', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_2', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_3', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_4', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_5', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='champ_eng_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='champInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100)),
                ('kor_name', models.CharField(max_length=100)),
                ('lobby_image_right', models.CharField(max_length=300)),
                ('lobby_image_left', models.CharField(max_length=300)),
                ('small_img', models.CharField(max_length=300)),
                ('ban_img', models.CharField(max_length=300)),
                ('voice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('ban_1', models.CharField(default='', max_length=100)),
                ('ban_2', models.CharField(default='', max_length=100)),
                ('ban_3', models.CharField(default='', max_length=100)),
                ('ban_4', models.CharField(default='', max_length=100)),
                ('ban_5', models.CharField(default='', max_length=100)),
                ('pick_1', models.CharField(default='', max_length=100)),
                ('pick_2', models.CharField(default='', max_length=100)),
                ('pick_3', models.CharField(default='', max_length=100)),
                ('pick_4', models.CharField(default='', max_length=100)),
                ('pick_5', models.CharField(default='', max_length=100)),
                ('ban_champ_1', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_2', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_3', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_4', models.CharField(default='', max_length=100, null=True)),
                ('ban_champ_5', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_1', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_2', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_3', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_4', models.CharField(default='', max_length=100, null=True)),
                ('pick_champ_5', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=200)),
                ('passwordBlue', models.CharField(default='', max_length=50)),
                ('passwordRed', models.CharField(default='', max_length=50)),
                ('timerB', models.CharField(default='30', max_length=10)),
                ('timerR', models.CharField(default='30', max_length=10)),
                ('flag', models.CharField(default='true', max_length=10)),
            ],
        ),
    ]
