# Generated by Django 3.1.6 on 2021-03-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomurl',
            name='flag',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
