# Generated by Django 3.1.6 on 2021-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickSystem', '0006_roomurl_clickflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomurl',
            name='selectChamp',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
